# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby_test_runner` gem.
# Please instead update this file by running `bin/tapioca gem ruby_test_runner`.

# source://ruby_test_runner//lib/ruby_test_runner/command.rb#3
module RubyTestRunner; end

# source://ruby_test_runner//lib/ruby_test_runner/command.rb#4
class RubyTestRunner::Command
  # @return [Command] a new instance of Command
  #
  # source://ruby_test_runner//lib/ruby_test_runner/command.rb#5
  def initialize(project_path, file_path, line_number); end

  # source://ruby_test_runner//lib/ruby_test_runner/command.rb#19
  def runner_command; end

  private

  # @return [Boolean]
  #
  # source://ruby_test_runner//lib/ruby_test_runner/command.rb#90
  def bin_rake?; end

  # @return [Boolean]
  #
  # source://ruby_test_runner//lib/ruby_test_runner/command.rb#86
  def bin_test?; end

  # @return [Boolean]
  #
  # source://ruby_test_runner//lib/ruby_test_runner/command.rb#112
  def bundle_rake?; end

  # @return [Boolean]
  #
  # source://ruby_test_runner//lib/ruby_test_runner/command.rb#82
  def bundler?; end

  # source://ruby_test_runner//lib/ruby_test_runner/command.rb#70
  def line_pattern; end

  # @return [Boolean]
  #
  # source://ruby_test_runner//lib/ruby_test_runner/command.rb#78
  def rails_bin_test?; end

  # @return [Boolean]
  #
  # source://ruby_test_runner//lib/ruby_test_runner/command.rb#120
  def rake_defines_test_task?(pwd); end

  # @return [Boolean]
  #
  # source://ruby_test_runner//lib/ruby_test_runner/command.rb#96
  def rspec_via_bin?; end

  # @return [Boolean]
  #
  # source://ruby_test_runner//lib/ruby_test_runner/command.rb#100
  def rspec_via_bundle?; end

  # @return [Boolean]
  #
  # source://ruby_test_runner//lib/ruby_test_runner/command.rb#107
  def rspec_via_rake?; end
end

# source://ruby_test_runner//lib/ruby_test_runner.rb#8
class RubyTestRunner::Error < ::StandardError; end

# source://ruby_test_runner//lib/ruby_test_runner/minitest_with_line_numbers.rb#6
class RubyTestRunner::MinitestWithLineNumbers
  # @return [MinitestWithLineNumbers] a new instance of MinitestWithLineNumbers
  #
  # source://ruby_test_runner//lib/ruby_test_runner/minitest_with_line_numbers.rb#33
  def initialize(code); end

  # source://ruby_test_runner//lib/ruby_test_runner/minitest_with_line_numbers.rb#37
  def pattern_for_line(line_number); end

  # rush hack for demo, fix later!
  #
  # source://ruby_test_runner//lib/ruby_test_runner/minitest_with_line_numbers.rb#48
  def test_command_for_line(test_name_or_line_number); end
end

# source://ruby_test_runner//lib/ruby_test_runner/minitest_with_line_numbers.rb#7
class RubyTestRunner::MinitestWithLineNumbers::TestClassVisitor < ::SyntaxTree::Visitor
  # @return [TestClassVisitor] a new instance of TestClassVisitor
  #
  # source://ruby_test_runner//lib/ruby_test_runner/minitest_with_line_numbers.rb#8
  def initialize; end

  # Returns the value of attribute class_name.
  #
  # source://ruby_test_runner//lib/ruby_test_runner/minitest_with_line_numbers.rb#13
  def class_name; end

  # source://ruby_test_runner//lib/ruby_test_runner/minitest_with_line_numbers.rb#15
  def visit_class(node); end
end

# source://ruby_test_runner//lib/ruby_test_runner/minitest_with_line_numbers.rb#20
class RubyTestRunner::MinitestWithLineNumbers::TestNameVisitor < ::SyntaxTree::Visitor
  # @return [TestNameVisitor] a new instance of TestNameVisitor
  #
  # source://ruby_test_runner//lib/ruby_test_runner/minitest_with_line_numbers.rb#21
  def initialize; end

  # Returns the value of attribute tests.
  #
  # source://ruby_test_runner//lib/ruby_test_runner/minitest_with_line_numbers.rb#26
  def tests; end

  # source://ruby_test_runner//lib/ruby_test_runner/minitest_with_line_numbers.rb#28
  def visit_def(node); end
end

# source://ruby_test_runner//lib/ruby_test_runner/version.rb#4
RubyTestRunner::VERSION = T.let(T.unsafe(nil), String)
